kind: pipeline
name: default

steps:
- name: Drone
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.
  - platformio run -d examples/zephyr-blink
  - platformio run -d examples/arduino-blink
