kind: pipeline
name: default

steps:
- name: Drone
  image: ubuntu
  commands:
  - apt update
  - apt install -y git gcc-arm-none-eabi cmake
  - git submodule update --init --recursive
  - cd src && mkdir build && cd build
  - cmake .. && make
