name: latest

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Download
      working-directory: src
      run: |
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
        tar -xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2

    - name: Build
      working-directory: src
      run: |
        mkdir build && cd build
        cmake -DMCU_TYPE=MM32F031 -D CROSS_COMPILER_PATH=../gcc-arm-none-eabi-10-2020-q4-major .. && make

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: upload-firmware
        path: src/build/
