name: gcc

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake

    - name: Build
      working-directory: src
      run: |
        mkdir build && cd build
        cmake .. && make

    - name: Build
      uses: actions/upload-artifact@v2
      with:
        name: upload-firmware
        path: src/build/
