name: nightly

on:
  schedule:
    - cron: '0 15 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake

    - name: Build
      working-directory: src
      run: |
        mkdir build && cd build
        cmake -DMCU_TYPE=MM32F031 .. && make
        mkdir -p ./output && cp *.elf "$_"

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: src/build/output/
